version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_ADDR=redis://redis:6379
    ports:
      - 5000:5000
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
